---
name: Dispatcher

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  dispatcher-job:
    name: Dispatcher
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Dispatcher"
