---
name: Dispatcher

on:
  workflow_dispatch:

jobs:
  dispatcher-job:
    name: Dispatcher
    runs-on: ubuntu-latest
    steps:
      - name: Get previous workflow status
        uses: github-actions-workflow_run-event/.github/workflows/status.yml@main
        id: last_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Success
        if: ${{ success() && steps.last_status.outputs.last_status == 'failure' }}
        run: echo "SUCCESS"
      - name: Run Failure
        if: ${{ success() && steps.last_status.outputs.last_status == 'success' }}
        run: echo "FAILURE"
