---
name: Preflight

on:
  workflow_run:
    workflows: [Dispatcher]
    types:
      - completed
  workflow_dispatch:

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - run: env
