---
name: Test

on: pull_request

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit_tests
      - run: echo "Test"
      
  test-job2:
    name: Test Step2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit_tests2
      - run: echo "Test2"
