---
name: Test

on: pull_request

permissions:
  pull-requests: write

jobs:
  test-job:
    if: "!contains(github.event.head_commit.message, '[skip actions]')"
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit_tests
        run: echo ${{ github.actor }}
      
  test-job2:
    if: "!contains(github.event.head_commit.message, '[skip actions]')"
    name: Test Step2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit_tests2
        run: echo ${{ github.actor }}
  dependabot:
    needs: [test-job, test-job2]
    runs-on: ubuntu-latest
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
