---
name: Test

on: pull_request

permissions:
  pull-requests: write

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit_tests
        run: echo "Test"
      
  test-job2:
    name: Test Step2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit_tests2
        run: echo "Test2"
  dependabot:
    needs: [test-job, test-job2]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
